/*
 * Copyright 2021 Branko Juric, Brady Wood
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gwen.core.report.rp

import RPConfig._

import gwen.core._

import scala.util.Try

import java.io.File

object RPSettings {

  private val rerun: Boolean = `rp.rerun`
  private val rerunOf: Option[String] = `rp.rerun.of`
  private lazy val rerunFile: File = new File(s"${GwenSettings.`gwen.output.dir`}/.rp-rerun.properties")

  def init(): Unit = {

    // force load mandatory settings
    `rp.endpoint`
    `rp.launch`
    `rp.project`
    `rp.key`
    `rp.rerun`
    `rp.rerun.of`
    `gwen.rp.send.meta`
    `gwen.rp.send.stepDefs`
    `gwen.rp.send.failed.stepDefs`
    `gwen.rp.send.failed.errorTrace`
    `gwen.rp.send.failed.envTrace`
    `gwen.rp.send.failed.hierarchy`
    `gwen.rp.send.failed.errorBlocks`
    `gwen.rp.send.breadcrumbs`
    `gwen.rp.send.tags`
    `gwen.rp.send.annotations`
    `gwen.rp.send.markdownBlocks`
    `gwen.rp.heartbeat.enabled`
    `gwen.rp.heartbeat.timeoutSecs`
    `gwen.rp.testCaseId.keys`
    `gwen.rp.debug`

    // load rerun settings
    if (rerun && rerunOf.isEmpty && rerunFile.exists()) {
      Settings.init(rerunFile)
    }
    
  }

  def writeRerunFile(uuid: String): Unit = {
    val content = 
      s"""|
          |# --------------------------------------------
          |# Report Portal Rerun File (generated by Gwen)
          |# --------------------------------------------
          |
          |# ID of last report portal launch. This property is implicitly loaded when 
          |# Gwen is launched with the rp.rerun=true property to facilitate rerun/merge 
          |# of the current execution results into the previous launch in report portal.
          |rp.rerun.of = $uuid
          |""".stripMargin
    rerunFile.writeText(content)
  }

  /* Provides access to the mandatory `rp.endpoint` report portal setting. */
  def `rp.endpoint`: String = Settings.get("rp.endpoint")

  /* Provides access to the mandatory `rp.launch` report portal setting. */
  def `rp.launch`: String = Settings.get("rp.launch")

  /* Provides access to the mandatory `rp.project` report portal setting. */
  def `rp.project`: String = Settings.get("rp.project")

  /* Provides access to the mandatory `rp.uuid` or `rp.api.key` report portal setting. */
  def `rp.key`: String = Settings.getOpt("rp.api.key").getOrElse(Settings.get("rp.uuid"))

  /* Provides access to the optional `rp.rerun` report portal setting. */
  def `rp.rerun`: Boolean = Settings.getBooleanOpt("rp.rerun").getOrElse(false)

  /* Provides access to the optional `rp.rerun.of` report portal setting. */
  def `rp.rerun.of`: Option[String] = Settings.getOpt("rp.rerun.of")

  /**
   * Provides access to the `gwen.rp.send.meta` property setting used to 
   * determine whether or not Meta specs are sent to the Report Portal (default value is `false`). 
   */
  def `gwen.rp.send.meta`: Boolean = Settings.getBoolean("gwen.rp.send.meta")

  /**
   * Provides access to the `gwen.rp.send.stepDefs` property setting used to 
   * determine how step defs are reported. Options include: inlined, nested, or none (default is `none`). 
   */
  def `gwen.rp.send.stepDefs`: StepDefFormat = getStepDefFormat("gwen.rp.send.stepDefs")

  /**
   * Provides access to the `gwen.rp.send.failed.StepDefs` property setting used to 
   * determine how failed step defs are reported. Options include: inlined, nested, or none (default is `inlined`). 
   * This setting is only honoured only if gwen.rp.stepDefs = none, otherwhise it takes on the 
   * same value as `gwen.rp.send.StepDefs`.
   */
  def `gwen.rp.send.failed.stepDefs`: StepDefFormat = getStepDefFormat("gwen.rp.send.failed.stepDefs")
  
  /**
   * Provides access to the `gwen.rp.send.failed.errorTrace` property setting used to 
   * determine how error traces are reported. 
   * Options include: inlined, attached, or none (default value is `none`). 
   */
  def `gwen.rp.send.failed.errorTrace`: ErrorReportingMode = getErrorReportingMode("gwen.rp.send.failed.errorTrace")

  /**
   * Provides access to the `gwen.rp.send.failed.envTrace` property setting used to 
   * determine how environment traces are reported. 
   * Options include: inlined, attached, or none (default value is `none`). 
   */
  def `gwen.rp.send.failed.envTrace`: ErrorReportingMode = getErrorReportingMode("gwen.rp.send.failed.envTrace")

  /**
   * Provides access to the `gwen.rp.send.failed.hierarchy` property setting used to 
   * determine how failed step hierarchies are reported. 
   * Options include: inlined, attached, or none (default value is `inlined`). 
   */
  def `gwen.rp.send.failed.hierarchy`: ErrorReportingMode = getErrorReportingMode("gwen.rp.send.failed.hierarchy")

  /**
   * Provides access to the `gwen.rp.send.failed.errorBlocks` property setting used to 
   * determine which step nodes in a failed call chain will have the error message appended 
   * to their descriptions. Options include: all, leaf, or none (default is none).
   */
  def `gwen.rp.send.failed.errorBlocks`: ErrorBlocks = getErrorBlocks("gwen.rp.send.failed.errorBlocks")
  
  /**
   * Provides access to the `gwen.rp.send.breadcrumbs` property setting used to 
   * determine whether to send breadcrumb (feature, rule, scenario, step names) attributes to 
   * report portal. Default is false.
   */
  def `gwen.rp.send.breadcrumbs`: Boolean = Settings.getBoolean("gwen.rp.send.breadcrumbs")

  /**
   * Provides access to the `gwen.rp.send.tags` property setting used to 
   * control whether or not to send tags in feature files to report portal. 
   * Default is `true`.
   */
  def `gwen.rp.send.tags`: Boolean = Settings.getBoolean("gwen.rp.send.tags")

  /**
   * Provides access to the `gwen.rp.send.annotations` property setting used to 
   * control whether or not to send annotations in feature files to send to report portal. 
   * Default is `false`.
   */
  def `gwen.rp.send.annotations`: Boolean = Settings.getBoolean("gwen.rp.send.annotations")

  /**
   * Provides access to the `gwen.rp.send.markdownBlocks` property setting used to 
   * determine whether or not to surround all markdown content with triple back ticks
   * so that it renedrs verbatim in markdown view. Default is true.
   */
  def `gwen.rp.send.markdownBlocks`: Boolean = Settings.getBoolean("gwen.rp.send.markdownBlocks")

  /**
   * Provides access to the `gwen.rp.heartbeat.enabled` property setting used to determine whether 
   * or not to check report portal connection before the first step of each scenario 
   * executes and fail fast when it goes offline. Default is true (enabled).
   */
  def `gwen.rp.heartbeat.enabled`: Boolean = Settings.getBoolean("gwen.rp.heartbeat.enabled", Some("gwen.rp.heartbeat"))

  /**
   * Provides access to the `gwen.rp.heartbeat.timeoutSecs` property setting used to timeout 
   * hearbeat requests. Default is 3 seconds. Only honoured if `gwen.rp.heartbeat.enabled` is `true`.
   */
  def `gwen.rp.heartbeat.timeoutSecs`: Int = Settings.getInt("gwen.rp.heartbeat.timeoutSecs")

  /**
    * Provides access to the `gwen.rp.testCaseId.keys` property setting used to control how
    * test case IDs are generated in report portal. Valid values include `nodePath+params` (default),
    * `sourceRef+params`, `nodePath`, `sourceRef`, or `auto`.
    */
  def `gwen.rp.testCaseId.keys`: TestCaseIdKeys = getTestCaseIdKeys("gwen.rp.testCaseId.keys")

   /**
   * Provides access to the `gwen.rp.debug` property setting used to 
   * control whether or not to send debug messages to report portal logs.
   * Default is false (don't send). 
   */
  def `gwen.rp.debug`: Boolean = Settings.getBoolean("gwen.rp.debug")

  private def getStepDefFormat(name: String): StepDefFormat = {
    Settings.getAndConvert(name, None, StepDefFormat.values.mkString(", ")) { value =>
      StepDefFormat.valueOf(value)
    }
  }

  private def getErrorReportingMode(name: String): ErrorReportingMode = {
    Settings.getAndConvert(name, None, ErrorReportingMode.values.mkString(", ")) { value =>
      ErrorReportingMode.valueOf(value)
    }
  }

  private def getErrorBlocks(name: String): ErrorBlocks = {
    Settings.getAndConvert(name, None, ErrorBlocks.values.mkString(", ")) { value =>
      ErrorBlocks.valueOf(value)
    }
  }
  
  private def getTestCaseIdKeys(name: String): TestCaseIdKeys = {
    Settings.getAndConvert(name, None, TestCaseIdKeys.values.mkString(", ")) { value =>
      TestCaseIdKeys.valueOf(value)
    }
  }

}
