# Default log level (trace, debug, info, warn, error, off)
org.slf4j.simpleLogger.defaultLogLevel=off

# Gwen log level
org.slf4j.simpleLogger.log.gwen=error

# Output target: System.out, System.err, or a file path
org.slf4j.simpleLogger.logFile=System.out

# Formatting options
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false
org.slf4j.simpleLogger.levelInBrackets=true
